#!/usr/bin/env python
# coding: utf-8

# # Understanding Multi-Armed Bandit Problem

# Importing neccesary libaries 
import numpy as np
import matplotlib.pyplot as plt

# Assigning value to the number of machines
number_of_slot_machines = int(input("The number of the slot machine: ")) 

# Creates an array of the size of the number of slot machines with Jackpot Probability values
np.random.seed(100)
JPs =  np.random.uniform(0,1, number_of_slot_machines)

# Printing the Jackpot Probability array i.e: JPs
print(JPs)

# Plotting the Jackpot Probability Values for the number of the Slot Machines
plt.bar(np.arange(len(JPs)),JPs)
plt.show()

# Key Highlights from the above graph
# First Machine agent tried its payout is generous but not the best
# Fourth Machine pays best i.e: 84% payout rate and its the best machine in the environment
# Fifth Machine has the worst odds of paying out a jackpot

# In the above code agent does not have any idea on the payout rates so it is discovering for best payout rate by pullying each slot machine. 
# Understanding Exploitation and Exploration Concept: In case agent would have just sticked to the first machine i.e: choosing explotation over exploration the agent would never have figured out the best playing slot machine 

# At start of our simulation we want our agent to assume tht Jackpot Probability of each slot machine is zero initially.So we are creating an array of zeros as Jackpot Probability
known_JPs = np.zeros(number_of_slot_machines)

# Printing the Jackpot Probability array of zeros
print (known_JPs)

# Creating a simulation of slot machine
def play_machine(slot_machine):
  x = np.random.uniform(0, 1)
  if (x <= JPs[slot_machine]):
    return(10)
  else:
    return(-1)

# When we will execute the above simulation of slot machine of the machine pays out a reward of 10 will be paid but if it does not a negative reward of 1 will be paid. In next step we are going to test out simulation.

# Test Slot Machine 4
for machines in range(10):
  print(play_machine(3))
print ("------")      
# Test Slot Machine 5
for machines in range(10):
  print(play_machine(4))

# Above as we are exploiting Machine 4 and Machine 5 ther is no guarantee of the output results. The results should be like majority of 10 values for Machine 4 and nearly all -1 values for Machine 5
# From our above analysis we can say simulated slot machine code is behaving as expected. Next we will understand the application of Epsilon Greedy Strategy which is focused towards Reinforcement Learning
